config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources 'articles', only: [:index]
  root 'articles#index'
  get 'articles/search', to: 'articles#search'
  get 'articles/trends', to: 'articles#trends'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 10, maximum: 70 }
  validates :content, presence: true, length: { minimum: 10, maximum: 400 }
end

app/models/query.rb
class Query < ApplicationRecord
  include PgSearch::Model

  pg_search_scope :search_similarity,
                  against: :query,
                  using: {
                    trigram: {
                      threshold: 0.2
                    }
                  }
  validates :query, presence: true
  validates :query, length: { minimum: 3, maximum: 40 }
  validates :user_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_session, only: [:search]
  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  def trends
    @queries = Query.where(user_id: session[:user_id])
  end

  def search
    @articles = if params[:query].present?
                  Article.where('title LIKE ?', "%#{params[:query]}%")
                else
                  Article.all
                end
    if turbo_frame_request?
      render partial: 'articles', locals: { articles: @articles }
    else
      render :index
    end
    save_query(params[:query], session[:user_id])
  end

  private

  def save_query(query, session)
    return if query.nil? || query.length < 3

    searched_query = Query.new(user_params)
    searched_query.user_id = session
    saved_query = Query.where(user_id: session)
    if saved_query.empty?
      searched_query.save
    else
      similar = saved_query.search_similarity(query)
      if similar.empty?
        searched_query.save
      elsif query.length > similar.first.query.length
        similar.first.update(query:)
      end
    end
  end

  def user_params
    params.permit(:query)
  end

  def check_session
    session[:user_id] = SecureRandom.urlsafe_base64(16) if session[:user_id].nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
  
<div class="xl:w-1/3 md:w-1/2 w-full p-4  shadow-inner ">
  <div id="<%= dom_id article %>">
    <div class="border border-gray-700 min-h-full grid content-between max-h-72 border-opacity-75 p-6 rounded-lg">
      <h2 class="text-lg text-white font-medium title-font truncate "><%= article.title%></h2>
      <p class="leading-relaxed text-base mb-3 truncate"><%= article.content%></p>
    </div>
  </div>
</div>

app/views/articles/_articles.html.erb
<%= turbo_frame_tag "articles" do %>
  <%= render articles %>
<% end %>

app/views/articles/_queries.html.erb
<div class="flex flex-wrap justify-center">
  <% queries.each do |query| %>
    <div class="m-5 pl-3 pr-3 h-8 inline-flex items-center justify-center rounded-md bg-gray-800 text-red-400 mb-4">
      <h2 class='text-sm font-semibold tracking-widest'><%= query.query%></h2>
    </div>
  <% end %>
</div>

app/views/articles/index.html.erb
<div class="pt-8">
  <%= link_to "See search trends",articles_trends_path(), class:"text-white m-5 bg-red-500 hover:bg-red-500 focus:ring-1 focus:outline-none focus:ring-red-300 font-medium rounded text-sm px-4 py-2"%>
</div>
<section class="text-gray-400 body-font bg-gray-900 min-h-screen grid content-between">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap w-full mb-20 flex-col items-center text-center">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-white">Figure out top articles</h1>
      <p class="lg:w-1/2 w-full leading-relaxed text-opacity-80">Search preciouse articles in real-time and remember your search trends</p>
      <%= form_with(url: articles_search_path, method: :get,class:"lg:w-1/2 md:w-full w-full mt-5" , data: {controller: "search-form", turbo_frame: "articles", turbo_action: "advance"}) do |form| %>
        <label class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-gray-300">Search</label>
        <div class="relative">
          <div class="flex absolute inset-y-0 left-0 items-center pl-3 pointer-events-none">
            <svg aria-hidden="true" class="w-5 h-5 text-gray-500 dark:text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path></svg>
          </div>
          <%= form.text_field :query, class: "focus:outline-none block p-4 pl-10 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border  focus:ring-red-500 focus:border-red-500 ", placeholder: 'Search something', data: {action: "input->search-form#search"} %>
        </div>
      <% end %>
    </div>
    <div class="flex flex-wrap -m-4">
      <%= render "articles", articles: @articles %>
    </div>
  </section>

app/views/articles/trends.html.erb
<section class="text-gray-400 body-font bg-gray-900 min-h-screen grid content-between">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap w-full mb-20 flex-col items-center text-center">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-white">Most recent trends!</h1>
      <%= render "queries", queries: @queries %>
    </div>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchAnalyticRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-gray-900">
  
    <%= yield %>
  </body>
</html>